// Code generated by hertz generator.

package show

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _essayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _essayevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getevaluatelogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createexerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _doexerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeexerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _simpleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsimpleexercisesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitfeedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applysignedurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ocrMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _daily_attendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dailyattendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdailyattendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _invitationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinvitationcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fillinvitationcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _evaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createexercisestreamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _essayevaluatestreamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bindauthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _classMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createclassMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getclassMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _joinclassMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listclassesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getclassmembersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _homeworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createhomeworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethomeworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gradehomeworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listhomeworksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethomeworksubmissionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submithomeworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _question_bankMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listquestionbanksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listhomeworksforstuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsubmissionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethomeworkevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsubmissionevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _correcthomeworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _evaluatemodifyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadsubmissionevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _modifysubmissionevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recorrecthomeworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendwechatmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletehomeworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _edithomeworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _isneedrenameMw() []app.HandlerFunc {
	// your code...
	return nil
}
