// Code generated by hertz generator. DO NOT EDIT.

package show

import (
	show "essay-show/biz/adaptor/controller/show"
	"github.com/cloudwego/hertz/pkg/app/server"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_class := root.Group("/class", _classMw()...)
		_class.POST("/create", append(_createclassMw(), show.CreateClass)...)
		_class.GET("/list", append(_listclassesMw(), show.ListClasses)...)
		{
			_members := _class.Group("/members", _membersMw()...)
			_members.POST("/bind", append(_bindclassmemberMw(), show.BindClassMember)...)
			_members.POST("/create", append(_createclassmembersMw(), show.CreateClassMembers)...)
			_members.POST("/edit", append(_editclassmembernameMw(), show.EditClassMemberName)...)
			_members.GET("/get", append(_getclassmembersMw(), show.GetClassMembers)...)
			_members.GET("/info", append(_getclassmemberinfoMw(), show.GetClassMemberInfo)...)
			_members.POST("/unbind", append(_unbindclassmemberMw(), show.UnbindClassMember)...)
			{
				_delete := _members.Group("/delete", _deleteMw()...)
				_delete.DELETE("/:memberId", append(_deleteclassmemberMw(), show.DeleteClassMember)...)
			}
		}
	}
	{
		_essay := root.Group("/essay", _essayMw()...)
		_essay.POST("/evaluate", append(_essayevaluateMw(), show.EssayEvaluate)...)
		_evaluate := _essay.Group("/evaluate", _evaluateMw()...)
		_evaluate.POST("/download", append(_downloadevaluateMw(), show.DownloadEvaluate)...)
		_evaluate.POST("/modify", append(_evaluatemodifyMw(), show.EvaluateModify)...)
		_evaluate.POST("/stream", append(_essayevaluatestreamMw(), show.EssayEvaluateStream)...)
		{
			_delete0 := _evaluate.Group("/delete", _delete0Mw()...)
			_delete0.DELETE("/:evaluateId", append(_deleteevaluateMw(), show.DeleteEvaluate)...)
		}
		_essay.POST("/like", append(_likeevaluateMw(), show.LikeEvaluate)...)
		_essay.POST("/logs", append(_getevaluatelogsMw(), show.GetEvaluateLogs)...)
	}
	{
		_exercise := root.Group("/exercise", _exerciseMw()...)
		_exercise.POST("/create", append(_createexerciseMw(), show.CreateExercise)...)
		_create := _exercise.Group("/create", _createMw()...)
		_create.POST("/stream", append(_createexercisestreamMw(), show.CreateExerciseStream)...)
		_exercise.POST("/do", append(_doexerciseMw(), show.DoExercise)...)
		_exercise.POST("/get", append(_getexerciseMw(), show.GetExercise)...)
		_exercise.POST("/like", append(_likeexerciseMw(), show.LikeExercise)...)
		{
			_simple := _exercise.Group("/simple", _simpleMw()...)
			_simple.POST("/list", append(_listsimpleexercisesMw(), show.ListSimpleExercises)...)
		}
	}
	{
		_feedback := root.Group("/feedback", _feedbackMw()...)
		_feedback.POST("/submit", append(_submitfeedbackMw(), show.SubmitFeedback)...)
	}
	{
		_homework := root.Group("/homework", _homeworkMw()...)
		_homework.POST("/create", append(_createhomeworkMw(), show.CreateHomework)...)
		_homework.POST("/edit", append(_edithomeworkMw(), show.EditHomework)...)
		_homework.GET("/list", append(_listhomeworksMw(), show.ListHomeworks)...)
		_homework.POST("/re-evaluate", append(_reevaluatehomeworkMw(), show.ReEvaluateHomework)...)
		_homework.POST("/recorrect", append(_recorrecthomeworkMw(), show.ReCorrectHomework)...)
		_homework.GET("/statistics", append(_gethomeworkstatisticsMw(), show.GetHomeworkStatistics)...)
		_homework.GET("/submission", append(_getsubmissionevaluateMw(), show.GetSubmissionEvaluate)...)
		_submission := _homework.Group("/submission", _submissionMw()...)
		_submission.POST("/download", append(_downloadsubmissionevaluateMw(), show.DownloadSubmissionEvaluate)...)
		_submission.POST("/modify", append(_modifysubmissionevaluateMw(), show.ModifySubmissionEvaluate)...)
		_homework.GET("/submissions", append(_getsubmissionsMw(), show.GetSubmissions)...)
		_homework.POST("/submit", append(_submithomeworkMw(), show.SubmitHomework)...)
		{
			_delete1 := _homework.Group("/delete", _delete1Mw()...)
			_delete1.DELETE("/:homeworkId", append(_deletehomeworkMw(), show.DeleteHomework)...)
		}
		{
			_lesson_plan := _homework.Group("/lesson_plan", _lesson_planMw()...)
			_lesson_plan.POST("/download", append(_downloadlessonplanMw(), show.DownloadLessonPlan)...)
		}
		{
			_user := _homework.Group("/user", _userMw()...)
			_user.GET("/submissions", append(_getusersubmissionsMw(), show.GetUserSubmissions)...)
		}
	}
	{
		_question_bank := root.Group("/question_bank", _question_bankMw()...)
		_question_bank.GET("/list", append(_listquestionbanksMw(), show.ListQuestionBanks)...)
	}
	{
		_sts := root.Group("/sts", _stsMw()...)
		_sts.POST("/apply", append(_applysignedurlMw(), show.ApplySignedUrl)...)
		_sts.POST("/ocr", append(_ocrMw(), show.OCR)...)
		_sts.POST("/send_verify_code", append(_sendverifycodeMw(), show.SendVerifyCode)...)
	}
	{
		_user0 := root.Group("/user", _user0Mw()...)
		_user0.POST("/bind_auth", append(_bindauthMw(), show.BindAuth)...)
		_user0.GET("/daily_attend", append(_dailyattendMw(), show.DailyAttend)...)
		_daily_attend := _user0.Group("/daily_attend", _daily_attendMw()...)
		_daily_attend.GET("/get", append(_getdailyattendMw(), show.GetDailyAttend)...)
		_user0.POST("/generate_url_link", append(_generateurllinkMw(), show.GenerateUrlLink)...)
		_user0.GET("/info", append(_getuserinfoMw(), show.GetUserInfo)...)
		_user0.POST("/sign_in", append(_signinMw(), show.SignIn)...)
		_user0.POST("/update", append(_updateuserinfoMw(), show.UpdateUserInfo)...)
		{
			_invitation := _user0.Group("/invitation", _invitationMw()...)
			_invitation.GET("/code", append(_getinvitationcodeMw(), show.GetInvitationCode)...)
			_invitation.POST("/fill", append(_fillinvitationcodeMw(), show.FillInvitationCode)...)
		}
	}
}
