// Code generated by hertz generator. DO NOT EDIT.

package main

import (
	handler "essay-show/biz/adaptor/controller"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
}
