// Code generated by hertz generator. DO NOT EDIT.

package main

import (
	handler "essay-show/biz/adaptor/controller"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// 静态文件服务 - 直接提供文件访问
	r.StaticFile("/static/test_stream.html", "./static/test_stream.html")
	r.StaticFile("/static/test_exercise_stream.html", "./static/test_exercise_stream.html")
}
	