// Code generated by hertz generator.

package show

import (
	"context"
	"essay-show/biz/adaptor"
	"essay-show/biz/application/dto/essay/show"
	"essay-show/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateClass .
// @router /class/create [POST]
func CreateClass(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.CreateClassReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ClassService.CreateClass(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// ListClasses .
// @router /class/list [GET]
func ListClasses(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.ListClassesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ClassService.ListClasses(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetClassMembers .
// @router /class/members/get [GET]
func GetClassMembers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.GetClassMembersReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ClassService.GetClassMembers(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// BindClassMember .
// @router /class/members/bind [POST]
func BindClassMember(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.BindClassMemberReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ClassService.BindClassMember(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// CreateClassMembers .
// @router /class/members/create [POST]
func CreateClassMembers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.CreateClassMembersReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ClassService.CreateClassMembers(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// EditClassMemberName .
// @router /class/members/edit [POST]
func EditClassMemberName(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.EditClassMemberNameReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ClassService.EditClassMemberName(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// UnbindClassMember .
// @router /class/members/unbind [POST]
func UnbindClassMember(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.UnbindClassMemberReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ClassService.UnbindClassMember(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// DeleteClassMember .
// @router /class/members/delete/:memberId [DELETE]
func DeleteClassMember(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.DeleteClassMemberReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ClassService.DeleteClassMember(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetClassMemberInfo .
// @router /class/members/info [GET]
func GetClassMemberInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.GetClassMemberInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ClassService.GetClassMemberInfo(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
