// Code generated by hertz generator.

package show

import (
	"context"
	"essay-show/biz/adaptor"
	"essay-show/biz/application/dto/essay/show"
	"essay-show/biz/infrastructure/util/log"
	"essay-show/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateHomework .
// @router /homework/create [POST]
func CreateHomework(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.CreateHomeworkReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.HomeworkService.CreateHomework(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// ListHomeworks .
// @router /homework/list [GET]
func ListHomeworks(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.ListHomeworksReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.HomeworkService.ListHomeworks(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SubmitHomework .
// @router /homework/submit [POST]
func SubmitHomework(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.SubmitHomeworkReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.HomeworkService.SubmitHomework(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetSubmissions .
// @router /homework/submissions [GET]
func GetSubmissions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.GetSubmissionsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.HomeworkService.GetSubmissions(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetSubmissionEvaluate .
// @router /homework/submission [GET]
func GetSubmissionEvaluate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.GetSubmissionEvaluateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.HomeworkService.GetSubmissionEvaluate(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// CorrectHomework .
// @router /homework/correct [POST]
func CorrectHomework(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.CorrectHomeworkReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(show.CorrectHomeworkResp)

	c.JSON(consts.StatusOK, resp)
}

// ModifySubmissionEvaluate .
// @router /homework/submission/modify [POST]
func ModifySubmissionEvaluate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.ModifySubmissionEvaluateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.HomeworkService.ModifySubmissionEvaluate(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// DownloadSubmissionEvaluate .
// @router /homework/submission/download [POST]
func DownloadSubmissionEvaluate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.DownloadSubmissionEvaluateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.HomeworkService.DownloadSubmissionEvaluate(ctx, &req)
	log.Info("下载批改结果: %+v", resp)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
