// Code generated by hertz generator.

package show

import (
	"context"

	"essay-show/biz/adaptor"
	show "essay-show/biz/application/dto/essay/show"
	"essay-show/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ListQuestionBanks 获取题库列表
// @router /question_bank/list [GET]
func ListQuestionBanks(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.ListQuestionBanksReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.QuestionBankService.ListQuestionBanks(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
