// Code generated by hertz generator.

package show

import (
	"context"

	show "essay-show/biz/application/dto/essay/show"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetUserProfile .
// @router /user/profile [GET]
func GetUserProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.GetUserProfileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(show.GetUserProfileResp)

	c.JSON(consts.StatusOK, resp)
}
